name: "Check Container Status"
author: "zethuman"
description: "Execute a job and check container status"
inputs:
  name:
    required: true
    description: "Name of the container to check"
  timeout:
    required: false
    default: 120
    description: "Timeout in seconds. Default is 120 seconds"
  interval:
    required: false
    default: 1
    description: "Interval of checking in seconds. Default is 1 second"
runs:
  using: "composite"
  steps:
    - name: "Check Status"
      shell: bash
      run: |
        echo "Waiting '${{ inputs.name }}' to be healthy in ${{ inputs.timeout }} seconds..."
        for i in `seq ${{ inputs.timeout }}`; do
          state=$(docker inspect -f '{{ .State.Health.Status }}' ${{ inputs.name }})
          return_code=$?
          if [ ! ${return_code} -eq 0 ]; then
            exit ${RETURN_ERROR}
          fi
          if [[ "${state}" == "healthy" ]]; then
            echo "Container is healthy after ${i} seconds."
            exit 0
          elif [[ "${state}" == "unhealthy" ]]; then
            echo "Container is unhealthy after ${i} seconds. Restarting..."
            docker restart ${{ inputs.name }}
          fi
          sleep ${{ inputs.interval }}
        done
        echo "Timeout exceeded. Try to increase timeout or find out the cause of the unhealthy container"
        exit 1